parameters:
#    dciss_my.example.class: dciss\MyBundle\Example

services:
#    dciss_my.example:
#        class: %dciss_my.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
